# Generated by Django 6.0.2 on 2026-02-17 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(choices=[('Malaria', 'Malaria'), ('Cholera', 'Cholera'), ('Typhoid', 'Typhoid'), ('COVID-19', 'COVID-19')], max_length=50)),
                ('region', models.CharField(max_length=100)),
                ('number_of_cases', models.PositiveIntegerField()),
                ('number_of_deaths', models.PositiveIntegerField(default=0)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
