# Generated by Django 6.0.2 on 2026-02-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_healthreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthreport',
            name='symptoms',
            field=models.ManyToManyField(to='reports.symptom'),
        ),
    ]
